000vin000/anabada2

pom.xml
src/main/resources/application.properties

JPA의존성 추가 어프로치 파일 수정

---

src/main/java/kr/co/anabada/item/controller/ImageRestController.java

이미지컨트롤러 -> 이미지레스트컨트롤러

---

src/main/java/kr/co/anabada/item/controller/ImageRestController.java
src/main/java/kr/co/anabada/item/repository/ImageRepository.java
src/main/java/kr/co/anabada/item/repository/ItemRepository.java
src/main/java/kr/co/anabada/item/service/ImageService.java

아이템넘버를 통해 아이템 이미지 1번을 요청할 수 있음
이미지 요청 경로를 수정해서 이미지를 정상적으로 호출할 수 있음

이미지 관련 문제 해결

---

src/main/java/kr/co/anabada/user/controller/UserJoinController.java
src/main/java/kr/co/anabada/user/controller/UserLoginController.java
src/main/java/kr/co/anabada/user/dto/UserJoinDTO.java
src/main/java/kr/co/anabada/user/dto/UserLoginDTO.java
src/main/java/kr/co/anabada/user/entity/User.java
src/main/java/kr/co/anabada/user/repository/UserJoinRepository.java
src/main/java/kr/co/anabada/user/repository/UserLoginRepository.java
src/main/java/kr/co/anabada/user/repository/UserRepository.java
src/main/java/kr/co/anabada/user/service/UserJoinService.java
src/main/java/kr/co/anabada/user/service/UserLoginService.java
src/main/resources/static/auth/join.html
src/main/resources/static/auth/login.html
src/main/resources/static/js/user/login.js
src/main/resources/static/js/user/register.js

회원가입, 로그인 기능만 구현

---

src/main/java/kr/co/anabada/WebConfig.java
src/main/java/kr/co/anabada/user/controller/UserJoinController.java
src/main/java/kr/co/anabada/user/controller/UserLoginController.java
src/main/java/kr/co/anabada/user/repository/UserJoinRepository.java
src/main/java/kr/co/anabada/user/service/UserJoinService.java
src/main/resources/static/auth/join.html
src/main/resources/static/auth/login.html
src/main/resources/static/js/user/join.js
src/main/resources/static/js/user/liveValidation.js
src/main/resources/static/js/user/login.js
src/main/webapp/WEB-INF/views/header.jsp

JWT로 로그인 상태 유지 만들예정
로그아웃기능 추가예정

회원가입 유효성 프론트 실시간유효성 검사 추가 프론트 백엔드 유혀성 검사 추가 메인페이지 경로 수정

---

src/main/resources/static/js/recent/addRecent.js

이미지 호출 경로 변경

---

pom.xml
src/main/java/kr/co/anabada/user/controller/UserLoginController.java
src/main/java/kr/co/anabada/user/util/JwtUtil.java
src/main/resources/static/js/user/authCheck.js
src/main/resources/static/js/user/login.js
src/main/resources/static/js/user/logout.js

jwt 토큰 (프론트) 추가

---

src/main/java/kr/co/anabada/item/repository/ItemRepository.java
src/main/java/kr/co/anabada/item/service/ImageService.java
src/main/java/kr/co/anabada/user/controller/SellerInfoRestController.java
src/main/java/kr/co/anabada/user/controller/SellerinfoController.java
src/main/java/kr/co/anabada/user/repository/SellerRepository.java
src/main/java/kr/co/anabada/user/service/SellerService.java
src/main/webapp/WEB-INF/views/item/review.jsp
src/main/webapp/WEB-INF/views/item/sellerinfo.jsp

Jhu_seller

---

src/main/java/kr/co/anabada/AnabadaApplication.java
src/main/java/kr/co/anabada/user/entity/Seller.java
src/main/java/kr/co/anabada/user/repository/BuyerRepository.java
src/main/java/kr/co/anabada/user/repository/SellerRepository.java
src/main/java/kr/co/anabada/user/scheduler/UserProfileScheduler.java

UserProfile 스케줄러 구현
- Seller 세부정보 => at 02:00
- Buyer의 sellerGrade => at 00:00 at 1 day

UserProfile 스케줄러 구현

---

src/main/java/kr/co/anabada/SecurityConfig.java
src/main/java/kr/co/anabada/jwt/JwtAuthenticationFilter.java
src/main/java/kr/co/anabada/jwt/JwtTokenHelper.java
src/main/java/kr/co/anabada/jwt/UserTokenInfo.java
src/main/java/kr/co/anabada/user/controller/UserInfoUpdateController.java
src/main/java/kr/co/anabada/user/controller/UserPinController.java
src/main/java/kr/co/anabada/user/dto/UserInfoUpdateRequestDto.java
src/main/java/kr/co/anabada/user/service/UserDetailsImpl.java
src/main/java/kr/co/anabada/user/service/UserDetailsServiceImpl.java
src/main/java/kr/co/anabada/user/service/UserPinService.java
src/main/java/kr/co/anabada/user/service/UserUpdateService.java
src/main/resources/static/auth/test-auth.html
src/main/resources/static/js/user/createpin.js
src/main/resources/static/js/user/fetchWithAuth.js
src/main/resources/static/js/user/goToUpdateInfo.js
src/main/resources/static/js/user/login.js
src/main/resources/static/js/user/pinAuth.js
src/main/resources/static/js/user/tokenUtil.js
src/main/resources/static/js/user/updateInfo.js
src/main/resources/static/user/createpin.html
src/main/resources/static/user/pinauth.html
src/main/resources/static/user/updateinfo.html
src/main/webapp/WEB-INF/views/header.jsp
src/main/webapp/WEB-INF/views/mypage/mypage_main.jsp

회원정보 수정 / 2차비밀번호 인증

---

src/main/java/kr/co/anabada/user/controller/UserProfileController.java
src/main/java/kr/co/anabada/user/dto/UserProfileDTO.java
src/main/java/kr/co/anabada/user/dto/UserProfileDetailDTO.java
src/main/java/kr/co/anabada/user/repository/UserProfileRepository.java
src/main/java/kr/co/anabada/user/service/UserProfileService.java
src/main/webapp/WEB-INF/views/user/userProfile.jsp

userProfile 구현

---

src/main/java/kr/co/anabada/item/repository/ItemRepository.java
src/main/java/kr/co/anabada/item/scheduler/ItemStatusScheduler.java

- WAITING => ACTIVE
- ACTIVE => RESERVED
- ACTIVE => SOLD

ItemStatusScheduler 구현

---

src/main/java/kr/co/anabada/SecurityConfig.java
src/main/java/kr/co/anabada/admin/controller/AnswerController.java
src/main/java/kr/co/anabada/admin/controller/DashboardController.java
src/main/java/kr/co/anabada/admin/controller/ManagementController.java
src/main/java/kr/co/anabada/admin/controller/NoticeController.java
src/main/java/kr/co/anabada/jwt/JwtAuthenticationFilter.java
src/main/java/kr/co/anabada/jwt/JwtUtil.java
src/main/java/kr/co/anabada/user/controller/QuestionController.java
src/main/java/kr/co/anabada/user/service/UserDetailsImpl.java
src/main/java/kr/co/anabada/user/service/UserDetailsServiceImpl.java
src/main/webapp/WEB-INF/views/admin/customerManagement.jsp
src/main/webapp/WEB-INF/views/admin/dailySalesDetails.jsp
src/main/webapp/WEB-INF/views/admin/monthlySalesDetail.jsp
src/main/webapp/WEB-INF/views/admin/noticeCreate.jsp
src/main/webapp/WEB-INF/views/admin/noticeUpdate.jsp
src/main/webapp/WEB-INF/views/admin/salesDashboard.jsp
src/main/webapp/WEB-INF/views/admin/weeklySalesDetail.jsp

관리자 페이지 관리자만 들어갈 수 있게 설정

---

src/main/java/kr/co/anabada/admin/service/AdminService.java
src/main/java/kr/co/anabada/coin/controller/CashToCoinController.java
src/main/java/kr/co/anabada/coin/controller/CoinRestController.java
src/main/java/kr/co/anabada/coin/controller/WithdrawalController.java
src/main/java/kr/co/anabada/coin/repository/ChangeCoinRepository.java
src/main/java/kr/co/anabada/coin/repository/ConversionRepository.java
src/main/java/kr/co/anabada/coin/service/ChangeCoinService.java
src/main/java/kr/co/anabada/coin/service/ConversionService.java
src/main/java/kr/co/anabada/coin/service/GoodsService.java
src/main/resources/static/js/coinToCash.js
src/main/resources/static/js/conversionCoinModal.js
src/main/webapp/WEB-INF/views/mypage/coinView.jsp
src/main/webapp/WEB-INF/views/mypage/toCash.jsp
src/main/webapp/WEB-INF/views/mypage/toCoin.jsp
src/main/webapp/WEB-INF/views/mypage/withdrawal.jsp

코인 -> 현금 전환 기능

---

src/main/java/kr/co/anabada/admin/controller/AnswerController.java
src/main/java/kr/co/anabada/admin/controller/AnswerRestController.java
src/main/java/kr/co/anabada/admin/entity/Answer.java
src/main/java/kr/co/anabada/admin/repository/AdminRepository.java
src/main/java/kr/co/anabada/admin/repository/AnswerRepository.java
src/main/java/kr/co/anabada/admin/service/AnswerService.java
src/main/java/kr/co/anabada/jwt/JwtAuthenticationFilter.java
src/main/java/kr/co/anabada/user/entity/Question.java
src/main/java/kr/co/anabada/user/service/UserDetailsImpl.java
src/main/webapp/WEB-INF/views/admin/customerManagement.jsp
src/main/webapp/WEB-INF/views/question/answer.jsp

AnswerRestController로 수정

---

src/main/java/kr/co/anabada/user/controller/UserInfoUpdateController.java
src/main/java/kr/co/anabada/user/controller/UserPinController.java
src/main/java/kr/co/anabada/user/dto/UserInfoUpdateRequestDto.java
src/main/java/kr/co/anabada/user/repository/UserUpdateRepository.java
src/main/java/kr/co/anabada/user/service/UserInfoUpdateService.java
src/main/java/kr/co/anabada/user/service/UserJoinService.java
src/main/resources/static/js/user/fetchWithAuth.js
src/main/resources/static/js/user/liveValidation.js
src/main/resources/static/js/user/updateInfo.js
src/main/resources/static/js/user/updateinfoCheck.js
src/main/resources/static/user/updateinfo.html
src/main/resources/updateinfoCheck.java

회원정보 수정 구현 + 유효성검사까지

---

src/main/java/kr/co/anabada/user/controller/QuestionRestController.java
src/main/webapp/WEB-INF/views/admin/customerManagement.jsp

고객관리 답변하기 삭제 수정

---

src/main/resources/static/css/favorpageStyle.css
src/main/resources/static/css/recentItem.css
src/main/webapp/WEB-INF/views/mypage/favorPage.jsp
src/main/webapp/WEB-INF/views/mypage/itemup.jsp
src/main/webapp/WEB-INF/views/mypage/recentItem.jsp

Jhu debug2

---

src/main/java/kr/co/anabada/admin/controller/NoticeController.java
src/main/java/kr/co/anabada/admin/controller/NoticeRestController.java
src/main/java/kr/co/anabada/admin/service/NoticeService.java
src/main/webapp/WEB-INF/views/admin/customerManagement.jsp
src/main/webapp/WEB-INF/views/admin/noticeCreate.jsp
src/main/webapp/WEB-INF/views/admin/noticeUpdate.jsp

NoticeRestController 추가, 공지사항 수정

---

src/main/resources/static/css/styleWeather.css
src/main/resources/static/js/WeatherForShop.js
src/main/resources/static/js/weather.js
src/main/webapp/WEB-INF/views/main/mainForm.jsp

메인 페이지 - 위치정보 동의 거부 -> 서울 기준으로 표시

---

src/main/java/kr/co/anabada/admin/controller/AcceptConversionController.java
src/main/java/kr/co/anabada/admin/controller/DepositWithdrawalController.java
src/main/java/kr/co/anabada/admin/controller/UserAdminController.java
src/main/java/kr/co/anabada/admin/controller/UserAdminRestController.java
src/main/java/kr/co/anabada/admin/entity/Admin.java
src/main/java/kr/co/anabada/admin/repository/AdminRepository.java
src/main/java/kr/co/anabada/admin/service/AdminService.java
src/main/webapp/WEB-INF/views/admin/acceptConversion.jsp
src/main/webapp/WEB-INF/views/admin/adminRole.jsp
src/main/webapp/WEB-INF/views/admin/customerManagement.jsp
src/main/webapp/WEB-INF/views/admin/depositWithdrawal.jsp
src/main/webapp/WEB-INF/views/admin/fees.jsp
src/main/webapp/WEB-INF/views/admin/salesDashboard.jsp

관리자 권한 설정 구현

---

src/main/java/kr/co/anabada/user/controller/IndividualUserLoginController.java
src/main/resources/static/js/user/individual/IndividualLogin.js

관리자 로그인 시 페이지 이동 수정

---

src/main/resources/static/auth/login/individual/IndividualLogin.html
src/main/resources/static/css/individualLogin.css
src/main/resources/static/js/user/individual/IndividualLogin.js
src/main/webapp/WEB-INF/views/mypage/mypage_main.jsp

로그인페이지 스타일 적용
마이페이지 불필요한 문구 제거

엔터로 로그인이 가능하도록 수정

---

src/main/resources/static/css/styleAdmin.css
src/main/resources/static/js/admin/adminRole.js
src/main/resources/static/js/admin/customerManagement.js
src/main/webapp/WEB-INF/views/admin/acceptConversion.jsp
src/main/webapp/WEB-INF/views/admin/adminRole.jsp
src/main/webapp/WEB-INF/views/admin/customerManagement.jsp
src/main/webapp/WEB-INF/views/admin/depositWithdrawal.jsp
src/main/webapp/WEB-INF/views/admin/fees.jsp
src/main/webapp/WEB-INF/views/admin/salesDashboard.jsp

관리자 페이지 수정

---

src/main/java/kr/co/anabada/item/service/ItemService.java
src/main/java/kr/co/anabada/user/entity/Seller.java

새로 셀러로 등록됨
셀러 업데이트 페이지가 필요할 것으로 사료됨

셀러로 등록되지 않은 회원이 신규등록을 할때 생기는 문제 해결

---

src/main/java/kr/co/anabada/admin/controller/UserAdminRestController.java
src/main/webapp/WEB-INF/views/admin/noticeCreate.jsp
src/main/webapp/WEB-INF/views/admin/noticeUpdate.jsp

관리자 페이지 공지사항 수정 + 마스터 계정만 관리자 권한 부여 가능

---

src/main/java/kr/co/anabada/jwt/JwtAuthenticationFilter.java
src/main/java/kr/co/anabada/jwt/JwtUtil.java
src/main/resources/static/js/user/individual/IndividualLogin.js

individualLogin.js : 토큰을 쿠키에도 발행하도록 수정
JwtAuthenticationFilter : 헤더에 토큰이 없으면 쿠키에서 찾도록 수정
JwtUtil : ROLE_ 이 두번 생성되는 것을 방지

관리자 페이지 접근기능 정상화

---

src/main/java/kr/co/anabada/buy/entity/Payment.java
src/main/java/kr/co/anabada/user/controller/QuestionController.java
src/main/java/kr/co/anabada/user/repository/QuestionRepository.java
src/main/java/kr/co/anabada/user/service/QuestionService.java
src/main/resources/static/css/notice.css
src/main/resources/static/css/question.css
src/main/resources/static/js/myQuestions.js
src/main/webapp/WEB-INF/views/admin/noticeCreate.jsp
src/main/webapp/WEB-INF/views/admin/noticeUpdate.jsp
src/main/webapp/WEB-INF/views/mypage/myQuestionDetail.jsp
src/main/webapp/WEB-INF/views/mypage/myQuestions.jsp
src/main/webapp/WEB-INF/views/mypage/noticeList.jsp
src/main/webapp/WEB-INF/views/question/answer.jsp
src/main/webapp/WEB-INF/views/question/questionUpdate.jsp
src/main/webapp/WEB-INF/views/question/write.jsp

css 적용, 문의하기 상세보기 페이지

---

src/main/java/kr/co/anabada/mypage/controller/MypageController.java
src/main/webapp/WEB-INF/views/mypage/mypage_main.jsp

마이페이지 컨트롤러에서 마이프로필로 이동하기 위한 수정

마이페이지에 마이프로필, 즐겨찾기 링크 추가

---

src/main/java/kr/co/anabada/buy/entity/Review.java
src/main/java/kr/co/anabada/buy/repository/PaymentRepository.java
src/main/java/kr/co/anabada/buy/repository/ReviewRepository.java
src/main/java/kr/co/anabada/user/dto/UserProfileDTO.java
src/main/java/kr/co/anabada/user/dto/UserProfileDashboardDTO.java
src/main/java/kr/co/anabada/user/repository/SellerRepository.java
src/main/java/kr/co/anabada/user/scheduler/UserProfileScheduler.java
src/main/java/kr/co/anabada/user/service/UserProfileSchedulerService.java
src/main/java/kr/co/anabada/user/service/UserProfileService.java
src/main/resources/static/js/user/individual/userProfile.js
src/main/resources/static/js/user/individual/userProfileUtil.js
src/main/webapp/WEB-INF/views/user/userProfile.jsp

- DTO build 시 누적판매액 필드 설정 누락 해결
- 표시 텍스트 변경 등 사소한 리팩토링

UserProfileScheduler 1달 주기 스케줄링 로직 구현

---

src/main/java/kr/co/anabada/admin/controller/DashboardController.java
src/main/java/kr/co/anabada/admin/controller/UserAdminRestController.java
src/main/java/kr/co/anabada/admin/entity/Admin.java
src/main/java/kr/co/anabada/jwt/JwtAuthHelper.java
src/main/java/kr/co/anabada/jwt/JwtAuthenticationFilter.java

UserAdminRestController 수정

---

src/main/resources/static/css/style.css
src/main/resources/static/css/styleCoinView.css
src/main/webapp/WEB-INF/views/mypage/mypage_main.jsp

사용자 정보 버튼 스타일 적용
